name: Auto-milestone
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - closed
      - ready_for_review

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Run auto-milestone
        uses: grafana/grafana-github-actions-go/auto-milestone@main
        with:
          pr: ${{ github.event.pull_request.number }}
          token: "wrong token"
