name: Backport PR creator
on:
  pull_request_target:
    types:
      - closed
      - labeled
concurrency:
  group: backport-pr-creator
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main   
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backport
        uses: ./actions/backport
        with:
          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          labelsToAdd: "add to changelog, backport"
          title: "[Backport to {{base}}] {{originalTitle}}"

