name: Backport PRs to a release branch
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backporter
        uses: ./actions/backport
        with:
          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
