name: Feature Toggle Cleanup

on:
  workflow_dispatch:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '30 10 * * *'
jobs:
    fetch:
        runs-on: ubuntu-latest    
        steps:
            - name: Check out the code
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                node-version: "20.x"
            - run: npm install csv-parse
            - name: Parse CVS file to see which Feature Toggles should be notified about
              id: parse-csv-file
              uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
              env:
                    FEATURE_TOGGLES_CSV_FILE_PATH: "pkg/services/featuremgmt/toggles_gen.csv"
              with:
                    script: |
                        const { default: cleanupFeatureFlags } = await import('${{ github.workspace }}/.github/workflows/scripts/feature-toggle-cleanup/feature-toggle-cleanup.mjs')                        
                        await cleanupFeatureFlags({github, context, core})