name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue projects
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: grafana
          REPO: "github-actions-testrepo"
          ISSUE: ${{ toJSON(github.event.issue) }}
        run: |
          gh api graphql -f query='
            query($n: Int!) {
              repository(name: $repo, owner: $org) {
                issue (number: $number) {
                  state
                  title
                  author {
                    url
                  }
              }
            }' -f repo=$REPO -F org=$ORGANIZATION -F number=$ISSUE
            
            echo Issue $ISSUE
      - name: Get Platform UX project data
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: grafana
          PROJECT_NUMBER: 313
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Date posted") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="Todo") |.id' project_data.json) >> $GITHUB_ENV

