name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue}}
    steps:
      - name: Get project number
        run: |
          echo Issue number $NUMBER search $SEARCH
        env:
          NUMBER: ${{ github.event.issue.number }}
          SEARCH: ${{ toJSON(github.event.issue.projectCards) }}
