name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue}}
    steps:
      - name: Get project number
        run: |
          echo Issue number $NUMBER projItems $PROJITEMS projNextItems $PROJNEXTITEMS proj $PROJ
        env:
          NUMBER: ${{ github.event.issue.number }}
          PROJITEMS: ${{ toJSON(github.event.issue.projectItems) }}
          PROJNEXTITEMS: ${{ toJSON(github.event.issue.projectNextItems) }}
          PROJ: ${{ toJSON(github.event.issue.projectV2.312) }}
