name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: grafana
          PROJECT_NUMBER: 313
        run: |
          project_data="$( gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER --jq '.data.organization.projectV2')"

          echo 'PROJECT_DATA='$project_data >> $GITHUB_ENV
          echo 'PROJECT_ID='$project_data.id >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(project_data.fields.nodes[] | select(.name== "Date posted") | .id) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(project_data.fields.nodes[] | select(.name== "Status") | .id) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(project_data.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="Todo") |.id) >> $GITHUB_ENV

