name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is already in board
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          ISSUEID: ${{ toJSON(github.event.issue.number) }}
        run: |
          gh api graphql -f query='
            query($issue: Int!, $org: String!, $repo: String!) {
              repository(name: $repo, owner: $org) {
                issue (number: $issue) {
                  projectCards {
                    nodes {
                      project {
                        name
                      }
                    }
                  }
                }
              }
            }' -f repo=$REPO -f org=$ORGANIZATION -f issue=$ISSUEID > issue_data.json
            
            echo 'ISSUE_DATA='$(issue_data.json) >> $GITHUB_ENV
      - name: Get Platform UX project data
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: grafana
          PROJECT_NUMBER: 313
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Date posted") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="Todo") |.id' project_data.json) >> $GITHUB_ENV

