name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue}}
    steps:
      - name: Get project number
        run: |
          echo Issue number $NUMBER project $PROJECT projects $PROJ search $SEARCH
        env:
          NUMBER: ${{ github.event.issue.number }}
          PROJECT: ${{ github.event.issue.projectV2 }}
          PROJECTS: ${{ github.event.issue.projectsNext }}
          SEARCH: ${{ toJSON(github.event.issue.projectsV2) }}
