name: issue-add-to-parent-project

on:
  issues:
    types: 
      - edited
    labels:
      - 'type/question'
    
jobs:
  add_to_parent_project:
    if: github.event.issue.number > 0
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is already in board
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          STATUS: "Status"
        run: |
          gh api graphql -f query='
            query($org: String!, $repo: String!, $status: String!) {
              repository(name: $repo, owner: $org) {
                issue (number: ${{ github.event.issue.number }}) {
                  projectItems(first:20) {
                    nodes {
                      fieldValueByName(name:$status) {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          optionId
                          name
                        }
                      },
                      project {
                        number,
                        title
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -f repo=$REPO -f status=$STATUS > projects_data.json
            
            echo 'PROJECTS='$(jq '.data.repository.issue.projectItems.nodes[]' projects_data.json) >> $GITHUB_ENV
            echo 'EXISTS='$(jq '.data.repository.issue.projectItems.nodes[] | select(.project.number==312) | .project.number' projects_data.json) >> $GITHUB_ENV
      - name: Get Platform UX project data
        env:
          GITHUB_TOKEN: ${{ secrets.MIHAELA_PROJECTS_TOKEN }}
          ORGANIZATION: grafana
          PROJECT_NUMBER: 313
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Date posted") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="Todo") |.id' project_data.json) >> $GITHUB_ENV

