# Workflow for skipping the Levitate detection
# (This is needed because if a workflow is not running due to a path filtering then Github will show it as pending.)

name: Levitate / Detect breaking changes

on:
  pull_request:
    paths-ignore:
      - "packages/**"

jobs:
  detect:
    name: Detect breaking changes
    runs-on: ubuntu-latest

    steps:
      - name: Skipping
        run: echo "Skipping, no build required."

        # Build and persist output as a JSON (we need to tell the report workflow that the check has been skipped)
      - name: Persisting the check output
        run: |
          mkdir -p ./levitate
          echo "{ \"shouldSkip\": true }" > ./levitate/result.json

      # Upload artifact (so it can be used in the more privileged "report" workflow)
      - name: Upload check output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: levitate
          path: levitate/
