name: PR Checks
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
      - edited
  issues:
    types:
      - milestoned
      - demilestoned
concurrency:
  group: pr-checks-${{ github.event.number }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/pr-checks
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-checks
