name: pr-comment-on-trigger

on:
  workflow_run:
    workflows: ["pr-trigger-workflow-in-main"]
    types: [completed]

jobs:
  notify:
    name: pr-comment-on-trigger
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: message
        path: path/to/artifact
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: path/to/artifact

    - name: Parse artifact
      uses: actions/github-script@v5
      id: parse-artifact
      with:
        script: |
          const fs = require('fs');

          const content = fs.readFileSync(`path/to/artifact/result.json`);
          const result = JSON.parse(content);

          for (const property in result) {
              core.setOutput(property, result[property]);
          }

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ github.event.workflow_run.pull_requests[0].number }}
        message: |
          ${{steps.parse-artifact.outputs.message}}