name: pr-comment-on-trigger

on:
  workflow_run:
    workflows: ["pr-trigger-workflow-in-main"]
    types: [completed]

jobs:
  notify:
    name: pr-comment-on-trigger
    runs-on: ubuntu-latest

    steps:
    - name: Comment on PR
      uses: actions/github-script@v5
      with:
        script: |
          console.log(JSON.stringify({
            workflow_run_event: "${{github.event.workflow_run.event }}",
            workflow_run_conclusion: "${{github.event.workflow_run.conclusion }}",
            workflow_run_id: ${{github.event.workflow_run.id }},
            workflow_run_url: "${{github.event.workflow_run.url }}",
            pull_requests: "${{github.event.workflow_run.pull_requests[0]}}",
          }, null, 4));

    # - name: Comment on PR
    #   if: ${{ steps.breaking-changes.outputs.is_breaking == 1 }}
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   with:
    #     number: ${{ github.event.number }}
    #     message: |
    #       ⚠️ &nbsp;&nbsp;**Possible breaking changes**

    #       _(Open the links below in a new tab to go to the correct steps)_

    #       ${{ steps.breaking-changes.outputs.message }}

    #       [Check console output](${{steps.get-job-link.outputs.result}})