name: PR Checks
on:
  pull_request:
    types:
      - opened
      - milestoned
      - synchronize
      - demilestoned

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: 34_feat
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/pr-checks
        with:
          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          configPath: pr-checks
