name: pr-comment-on-trigger

on:
  workflow_run:
    workflows: ["pr-trigger-workflow-in-main"]
    types: [completed]

jobs:
  notify:
    name: pr-comment-on-trigger
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install adm-zip

    - name: Download artifact
      uses: actions/github-script@v5
      id: download-artifact
      with:
        script: |
          const runId = "${{github.event.workflow_run.id }}";
          const script = require('./.github/workflows/scripts/download-artifact-from-workflow.js');
          return await script({ github, context, core, runId });

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ github.event.workflow_run.pull_requests[0].number }}
        message: |
          ${{steps.download-artifact.outputs.result.message}}