name: pr-comment-on-trigger

on:
  workflow_run:
    workflows: ["pr-trigger-workflow-in-main"]
    types: [completed]

jobs:
  notify:
    name: pr-comment-on-trigger
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      uses: actions/github-script@v5
      with:
        script: |
          console.log(JSON.stringify({
            workflow_run_event: "${{github.event.workflow_run.event }}",
            workflow_run_conclusion: "${{github.event.workflow_run.conclusion }}",
            workflow_run_id: ${{github.event.workflow_run.id }},
            workflow_run_url: "${{github.event.workflow_run.url }}",
            pull_request_id: "${{github.event.workflow_run.pull_requests[0].id}}",
            pull_request_number: "${{github.event.workflow_run.pull_requests[0].number}}",
            pull_request_url: "${{github.event.workflow_run.pull_requests[0].url}}",
          }, null, 4));

    - name: Get artifact
      uses: actions/download-artifact@v2
      with:
        name: message

    - name: display downloads
      run: ls -R

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ github.event.workflow_run.pull_requests[0].number }}
        message: |
          This is a comment from the "pr-comment-on-trigger" from main