name: Run commands when pull requests are opened/updated
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          configPath: pr-commands
