name: pr-comment-on-trigger

on:
  workflow_run:
    workflows: ["pr-trigger-workflow-in-main"]
    types: [completed]

jobs:
  notify:
    name: pr-comment-on-trigger
    runs-on: ubuntu-latest

    steps:
    - name: 'Download artifact'
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');

          const { owner, repo } = context.repo;
          const runId = "${{ github.event.workflow_run.id }}";
          const artifactName = "message";
          const artifacts = await github.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: runId,
          });
          const artifact = artifacts.data.artifacts.find(a => a.name === artifactName);
        
          if (!artifact) {
              throw new Error(`Could not find artifact ${ artifactName } in workflow (${ runId })`);
          }

          const download = await github.actions.downloadArtifact({
              owner,
              repo,
              artifact_id: artifact.id,
              archive_format: 'zip',
          });

          fs.writeFileSync('${{ github.workspace }}/tmp/${ artifactName }.zip', Buffer.from(download.data));
  
    - name: Unzip artifact
      run: unzip pr.zip

    - name: Parse artifact
      id: parse-artifact
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');

          const content = fs.readFileSync(`tmp/result.json`);
          const result = JSON.parse(content);

          for (const property in result) {
              core.setOutput(property, result[property]);
          }

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ github.event.workflow_run.pull_requests[0].number }}
        message: |
          ${{steps.parse-artifact.outputs.message}}