# name: schedule-test

# on:
#   schedule:
#   - cron:  "*/5 * * * *"  

# jobs:
#   schedule-test:
#     if: github.repository == 'grafana/github-actions-testrepo'
#     runs-on: ubuntu-latest
#     steps:
#     - name: schedule-test      
#       run: | 
#           echo "running"