name: schedule-test

on:
  schedule:
  - cron:  "*/5 * * * *"  

jobs:
  schedule-test:
    runs-on: ubuntu-latest
    steps:       
    - name: schedule-test
      if: github.repository == 'grafana/github-actions-testrepo'
      run: | 
          echo "running"