name: test-pr-target
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - closed
      - milestoned
      - demilestoned

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Test echo
        run: echo "this ran on an event ${{ github.event_name }} / ${{ github.event.action }}"
