name: Update epic trending field

on:
  issue_comment:
    types:
      - created

jobs:
  update-trending:
    name: Update epic trending field
    runs-on: ubuntu-latest
    steps:
      - id: get-project-id
        uses: monry/actions-get-project-id@v2
        with:
          # Personal Access Token that with `org:read` are granted.
          github-token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}

          # Owner name of project
          project-owner: 'grafana'

          # Number of project
          # 
          # The project number is the number shown in the URL or list
          # https://github.com/users/monry/projects/123
          #                                         ^^^
          project-number: ${{ vars.GH_PROJECT_NUMBER }}
      - name: Output project id
        run: |
          echo ${{ steps.get-project-id.outputs.project-id }}
      - id: get-item-id
        uses: monry/actions-get-project-item-id@v2
        with:
          # Personal Access Token that with `repo` and `org:read` are granted.
          github-token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          project-id: ${{ steps.get-project-id.outputs.project-id }}
          issue-id: ${{ github.event.issue.node_id }}
      - name: Output item id
        run: |
          echo ${{ steps.get-item-id.outputs.project-item-id }}
      - id: extract-trend
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '<!-- data key="trending" start -->([\s\S]*?)<!-- data end -->'
          regex_flags: 'gmi'
          search_string: ${{ github.event.comment.body }}
      - name: Output trend
        run: |
          echo ${{ steps.extract-trend.outputs.first_match }}
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/grafana/projects/${{ vars.GH_PROJECT_NUMBER }}
          github-token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          item-id: ${{ steps.get-item-id.outputs.project-item-id }}
          field-keys: Trending
          field-values: ${{ steps.extract-trend.outputs.first_match }}
  
