name: Update changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true        
        description: Needs to match, exactly, the name of a milestone
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: feat/add-default-labels-to-changelog-pr
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run update changelog
        uses: ./actions/update-changelog
        with:
          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          metricsWriteAPIKey: ${{secrets.GRAFANA_MISC_STATS_API_KEY}}
